{"timestamp": "2025-07-26T17:11:56.803241", "level": "ERROR", "logger": "__main__", "message": "Failed to connect to Canvas", "module": "logger", "function": "_log", "line": 253, "thread_id": 140589811022784, "process_id": 9414, "data": {"exception_type": "InvalidAccessToken", "exception_message": "[{'m***.'}]", "traceback": "Trac***'}]\n"}, "context": {}}
{"timestamp": "2025-07-26T23:50:26.405017", "level": "ERROR", "logger": "src.core.file_manager", "message": "Failed to initialize paths", "module": "logger", "function": "_log", "line": 253, "thread_id": 140590886984640, "process_id": 7691, "data": {"exception_type": "NameError", "exception_message": "name***ined", "traceback": "Trac***ned\n"}, "context": {}}
{"timestamp": "2025-07-26T23:50:26.411498", "level": "ERROR", "logger": "src.core.file_manager", "message": "Failed to initialize settings", "module": "logger", "function": "_log", "line": 253, "thread_id": 140590886984640, "process_id": 7691, "data": {"exception_type": "NameError", "exception_message": "name***ined", "traceback": "Trac***ned\n"}, "context": {}}
{"timestamp": "2025-07-26T23:59:03.211925", "level": "ERROR", "logger": "src.core.file_manager", "message": "Failed to initialize paths", "module": "logger", "function": "_log", "line": 253, "thread_id": 140670951734208, "process_id": 8370, "data": {"exception_type": "NameError", "exception_message": "name***ined", "traceback": "Trac***ned\n"}, "context": {}}
{"timestamp": "2025-07-26T23:59:03.214307", "level": "ERROR", "logger": "src.core.file_manager", "message": "Failed to initialize settings", "module": "logger", "function": "_log", "line": 253, "thread_id": 140670951734208, "process_id": 8370, "data": {"exception_type": "NameError", "exception_message": "name***ined", "traceback": "Trac***ned\n"}, "context": {}}
{"timestamp": "2025-07-27T00:18:34.653102", "level": "ERROR", "logger": "src.core.orchestrator", "message": "Error during orchestrator cleanup", "module": "logger", "function": "_log", "line": 253, "thread_id": 140514974788544, "process_id": 10042, "data": {"exception_type": "AttributeError", "exception_message": "'Pro***nup'", "traceback": "Trac***up'\n"}, "context": {}}
{"timestamp": "2025-07-27T00:19:14.765133", "level": "ERROR", "logger": "src.core.orchestrator", "message": "Error during orchestrator cleanup", "module": "logger", "function": "_log", "line": 253, "thread_id": 140178750196672, "process_id": 10110, "data": {"exception_type": "AttributeError", "exception_message": "'Pro***nup'", "traceback": "Trac***up'\n"}, "context": {}}
